export enum Commands {
  north = 'north',
  n = 'n',
  south = 'south',
  s = 's',
  east = 'east',
  e = 'e',
  west = 'west',
  w = 'w',
  look = 'look',
  l = 'l',
  inventory = 'inventory',
  inv = 'inv',
  i = 'i',
  quit = 'quit',
  q = 'q',
  take = 'take',
  t = 't',
  drop = 'drop',
  d = 'd',
  equip = 'equip',
  eq = 'eq',
  wear = 'wear',
}